---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      traefik_ver:
        major: 1
        minor: 7
        patch: 17
  tasks:
    - command: /usr/local/bin/traefik version
      register: traefik_test_output
    - debug:
        msg: '{{ traefik_test_output.stdout }}'
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/traefik version
      register: traefik_test2_output
    - debug:
        msg: '{{ traefik_test2_output.stdout }}'
