---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      traefik_major_ver: 1
      traefik_minor_ver: 7
      traefik_patch_ver: 17
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/traefik version
      register: traefik_test_output
    - debug:
        msg: '{{ traefik_test_output.stdout }}'
