---
- name: Testing andrewrothstein.traefik (v1)
  hosts: all
  vars:
    traefik_ver:
      major: 1
      minor: 7
      patch: 17
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'traefik version'
      ansible.builtin.command: /usr/local/bin/traefik version
      changed_when: false
      register: traefik_test_output
    - name: Output of 'traefik version'
      ansible.builtin.debug:
        msg: '{{ traefik_test_output.stdout }}'
- name: Testing andrewrothstein.traefik (v2+)
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'traefik version'
      ansible.builtin.command: /usr/local/bin/traefik version
      changed_when: False
      register: traefik_test2_output
    - name: Output from 'traefik version'
      ansible.builtin.debug:
        msg: '{{ traefik_test2_output.stdout }}'
