---
- name: downloading {{ traefik_url }} to {{ traefik_target_bin }}
  become: true
  become_user: root
  get_url:
    url: '{{ traefik_url }}'
    dest: '{{ traefik_target_bin }}'
    checksum: '{{ traefik_checksum }}'
    mode: 0755
- name: linking {{ traefik_fq_target_link }} to {{ traefik_target_bin }}
  become: true
  become_user: root
  file:
    src: '{{ traefik_target_bin }}'
    dest: '{{ traefik_fq_target_link }}'
    state: link
