---
- name: Downloading {{ traefik_url }} to {{ traefik_target_bin }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ traefik_url }}'
    dest: '{{ traefik_target_bin }}'
    checksum: '{{ traefik_checksum }}'
    mode: '755'
- name: Linking {{ traefik_fq_target_link }} to {{ traefik_target_bin }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ traefik_target_bin }}'
    dest: '{{ traefik_fq_target_link }}'
    state: link
