---
- name: Look for install in {{ traefik_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ traefik_install_dir }}'
  changed_when: false
  register: traefik_binary
- name: Downloading and installing traefik
  when: not traefik_binary.stat.exists
  block:
    - name: Downloading {{ traefik_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ traefik_url }}'
        dest: '{{ traefik_tmp_archive }}'
        mode: '644'
        checksum: '{{ traefik_checksum }}'
    - name: Mkdir {{ traefik_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ traefik_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ traefik_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ traefik_tmp_archive }}'
        dest: '{{ traefik_install_dir }}'
        creates: '{{ traefik_target_bin }}'
  always:
    - name: Rm {{ traefik_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ traefik_tmp_archive }}'
        state: absent
- name: Linking {{ traefik_fq_target_link }} to {{ traefik_target_bin }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ traefik_target_bin }}'
    dest: '{{ traefik_fq_target_link }}'
    state: link
